export type AllIconNames =
  | 'icon_info'
  | 'icon_logo'
  | 'icon_search'
  | 'icon_terminal'
  | 'icon_link'
  | 'icon_bancolombia'
  | 'icon_mastercard'
  | 'icon_other_payment'
  | 'icon_nequi'
  | 'icon_visa'
  | 'icon_daviplata'
  | 'icon_pse'
  | 'icon_filter'
  | 'icon_close'
